[default]
hoge = "default hoge"

[default.apple.banana]
cow = "hello"
panda = "bow"

[dev]
hoge = "dev hoge"

[dev.apple.banana]
cow = "dev hello"
panda = "dev bow"

[prod]
hoge = "prod hoge"

[global]
hoge = "global hoge"

[default.databases.hoge]
url = "postgres://user:password@localhost/hoge"

[dev.databases.hoge]
url = "postgres://user:password@dev/hoge"